Test Harness
convict-git/KoraKaagaz pull request #128
Opened 2020-11-23 19:04 UTC by Rahul-R5

Contains complete implementation of test harness
Closes #107 Result logging
Closes #103 Related issue
Closes #61 Skeleton code
Closes #74 Overall

2020-11-23 22:00 UTC, convict-git requested changes
@Rahul-R5 Please get the things fixed.
I'm not sure why PR coming from the Infrastructure team has compilation issues.
Is the team not using Eclipse as suggested or any other Java IDE?

And are the codes not pulled locally for testing and reviewing at L2? Is the code just briefly reviewed from Github's UI and sent for merge at L1? 

I see some wrong methods and a lot of undeclared variables. :disappointed: PR coming at L2 is supposed to be deployable. Other teams are writing tests for their modules and these codes are not even checked for standalone compilation issues.

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +        String absPath = tests[i].getAbsolutePath();
`getAbsolutePath()` is a method for `File` Class. You are applying it on a `String`. 
If you were programming on a Java supported IDE, it must have shown an error.

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +            logger.log(ModuleID.TEST, LogLevel.INFO, Integer.toString(failedNumberOfTests)+". "+testName+": "+test.getError());
`testName` isn't defined at all. Neither it's a class variable nor a local variable.

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +      logger.log(ModuleID.TEST, LogLevel.WARNING, "Exception in module: "+strModule+" >> "+e);
Again, `strModule` isn't defined at all.

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +           }
`testName` not defined :shrug:

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +        logger.log(ModuleID.TEST, LogLevel.INFO, Integer.toString(failedNumberOfTests)+". "+testName+" :"+test.getError());
`testName` not defined

2020-11-23 22:00 UTC, convict-git commented on src/infrastructure/validation/testing/TestHarness.java
> +    logger.log(ModuleID.TEST, LogLevel.INFO, "Total Number of Successful Tests: "+Integer.toString(successfulNumberOfTests));
```suggestion
    logger.log(
       ModuleID.TEST, 
       LogLevel.INFO, 
       "Total Number of Successful Tests: "
       + Integer.toString(successfulNumberOfTests)
    );
```

All the logs can be changed to this format.

2020-11-24 04:04 UTC, Rahul-R5 commented
@convict-git Yes, I am aware it will have errors. That's why I informed you that it is not tested yet and I didn't put up a "Ready for review" comment on this PR. Why did you assume that this was the final version and needed to be reviewed? I merely created this PR for the progress to be tracked, did not request a review yet.

2020-11-24 07:09 UTC, closed without merging

2020-11-24 08:28 UTC, convict-git commented
> Why did you assume that this was the final version and needed to be reviewed?

Multiple reasons but the main one "There was no [WIP] tag"

@Rahul-R5 Why is the PR closed?

2020-11-24 08:56 UTC, Rahul-R5 commented
> @Rahul-R5 Why is the PR closed?

Branch was resetted and it auto closed. I'll make a new one.