Module tests and spec changes
convict-git/KoraKaagaz pull request #168
Opened 2020-12-04 13:42 UTC by sravand123

2020-12-04 13:51 UTC, convict-git requested changes
Also, every place in your module where you have `if`, `else`, `while`, `for` et cetera, should have `{ }` irrespective of how many statements it has inside it (be it one or more).

Eg. 
```diff
- if (condition) return true;
+ if (condition) {
+     return true;
+ }
```

2020-12-04 13:51 UTC, convict-git commented on src/networking/testSimulator/TestSimulator.java
> +
Else let the tester know that it expects some arguments.

2020-12-04 13:51 UTC, convict-git commented on src/networking/testSimulator/Message.java
> +	      return false;
Indentation.
The two conditions in if can be kept multiline.

2020-12-04 13:51 UTC, convict-git commented on src/networking/testSimulator/Client.java
> +					  Stopper stopper
Fix indentation to keep it consistent with other files.
If you don't see the difference on your local editor, check this on the GitHub file viewer, you will understand the difference.

2020-12-04 13:51 UTC, convict-git commented on src/networking/testSimulator/Client.java
> +										stopper
Fix indentation

2020-12-04 13:51 UTC, convict-git commented on src/networking/testSimulator/Client.java
> +									);
Fix indentation

2020-12-05 05:52 UTC, sravand123 commented on src/networking/testSimulator/Client.java
> +									);
@convict-git  ready to be merged

2020-12-05 07:18 UTC, merged