Master2
convict-git/KoraKaagaz pull request #21
Opened 2020-10-19 07:09 UTC by sakshi1603

Closes #19 #18 #17 #15 #14 #13 #12 #10 #4

2020-10-26 06:43 UTC, convict-git requested changes
Kindly refer [Google Java Guidelines](https://google.github.io/styleguide/javaguide.html) and make necessary changes. Also reviewers at L2, please make a note of this.

2020-10-26 06:43 UTC, convict-git commented on src/processing/IDrawShapes.java
> +    void draw_circle(Pixel center, float radius);
[Coding convention for methods](https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names
)
Please refer to the coding conventions and do necessary changes.

2020-10-26 06:43 UTC, convict-git commented on src/processing/Processor.java
> +	public void draw_circle(Pixel center, float radius) {
Please keep consistency in the coding standards. lower camel case is expected for method names.
[Method names convention](https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names)

2020-10-26 06:43 UTC, convict-git commented on src/processing/IUser.java
> +    // parameter: userName - user name
Please refer to the Javadoc formatting guidelines. Kindly make use of block tags
[Java Formatting](https://google.github.io/styleguide/javaguide.html#s7-javadoc)

2020-10-26 20:24 UTC, himanshu2047 commented
Ready for merge

2020-10-26 20:52 UTC, convict-git commented
Amazing work! Thanks, guys. :+1:  Will see tomorrow morning and merge soon. 
@muhammedyaseen-git Kindly review once, it's pending right now from your side.

2020-10-27 16:35 UTC, muhammedyaseen-git approved these changes

2020-10-27 21:07 UTC, convict-git approved these changes

2020-10-27 21:18 UTC, convict-git commented
Can you please change the Interfaces mentioned in the specs to follow the guidelines as you did for the actual interfaces? Most people will follow the documentation to understand the interface, and currently, there's a mismatch.

2020-10-28 09:35 UTC, convict-git approved these changes

2020-10-29 07:50 UTC, merged