add Processing-Team-Lead-Spec
convict-git/KoraKaagaz pull request #5
Opened 2020-10-06 17:52 UTC by sakshi1603

Closes convict-git/KoraKaagaz#4

2020-10-06 18:09 UTC, convict-git requested changes
Please follow a directory based structure. You can refer [Infrastructure Modules PR on team lead spec](https://github.com/convict-git/KoraKaagaz/pull/3)
`Processing/Specs/team-lead-spec.md`

2020-10-07 06:04 UTC, muhammedyaseen-git approved these changes

2020-10-07 06:20 UTC, muhammedyaseen-git commented
@sakshi1603 Are the dependencies with the other modules communicated to them?

2020-10-07 06:41 UTC, sakshi1603 commented
Yes, the interface was shared with UI team. Also networking team had shared their interface with us.

2020-10-29 07:50 UTC, merged